import os

JIRA_BASE_URL = os.getenv("JIRA_BASE_URL")
JIRA_API_EMAIL = os.getenv("JIRA_API_EMAIL")
JIRA_API_TOKEN = os.getenv("JIRA_API_TOKEN")
JIRA_PROJECT_KEY = os.getenv("JIRA_PROJECT_KEY")
JIRA_BOARD_ID = os.getenv("JIRA_BOARD_ID")
AUTH_HEADER_B64 = os.getenv("AUTH_HEADER_B64")
PLAYWRIGHT_HEADLESS = os.getenv("PLAYWRIGHT_HEADLESS")
JIRA_PASSWORD = os.getenv("JIRA_PASSWORD")
