*** Variables ***
${JIRA_BASE_URL}    https://henna0813taneja.atlassian.net
${PROJECT_KEY}      SCRUM
${AUTH_HEADER}      Basic aGVubmF0YW5lamE3MDZAZ21haWwuY29tOkFUQVRUM3hGZkdGMDItTmc0VndITF9NT2xHUFZRYWpMYzhRMUNBVlRCSERVWThQS3ZOWmVkVHNXbVlnNUFoQTN0bGpKVXNxRHdyNVZZVnZsS3p4eWNNc21HOHBwTy1EX1ktdU1GX0h3OWxVZjBjWUFDQ0NWelRNSWpVaTUwUmcwUGpMSzdnaDEwMEJvckdGSGtTQXgzZGR2M2hDWW9aalFWNXdmZWdEYmIzamwxMVhVdG9WNXIyaz1ENUU0RjgwQg==